import React, { useState } from 'react';
import { parseHandFormat, type ParsedHandData } from '../../lib/poker/utils/handFormatParser';

interface HandComparisonModalProps {
  generatedHand: string; // The hand generated by our tool
  expectedHand?: string; // Optional: pre-filled expected hand
  onClose: () => void;
}

interface ComparisonResult {
  field: string;
  expected: string;
  actual: string;
  match: boolean;
}

export const HandComparisonModal: React.FC<HandComparisonModalProps> = ({ generatedHand, expectedHand: initialExpectedHand, onClose }) => {
  const [expectedHand, setExpectedHand] = useState(initialExpectedHand || '');
  const [comparisonResults, setComparisonResults] = useState<ComparisonResult[]>([]);
  const [showResults, setShowResults] = useState(false);

  const compareHands = () => {
    const generated = parseHandFormat(generatedHand);
    const expected = parseHandFormat(expectedHand);

    if (!generated || !expected) {
      alert('Failed to parse one or both hands. Please check the format.');
      return;
    }

    const results: ComparisonResult[] = [];

    // Compare hand number
    results.push({
      field: 'Hand Number',
      expected: expected.header.handNumber,
      actual: generated.header.handNumber,
      match: expected.header.handNumber === generated.header.handNumber
    });

    // SKIP: Start time and End time comparison (timestamps are ignored)

    // Compare SB
    results.push({
      field: 'Small Blind',
      expected: expected.header.sb.toString(),
      actual: generated.header.sb.toString(),
      match: expected.header.sb === generated.header.sb
    });

    // Compare BB
    results.push({
      field: 'Big Blind',
      expected: expected.header.bb.toString(),
      actual: generated.header.bb.toString(),
      match: expected.header.bb === generated.header.bb
    });

    // Compare Ante
    results.push({
      field: 'Ante',
      expected: expected.header.ante.toString(),
      actual: generated.header.ante.toString(),
      match: expected.header.ante === generated.header.ante
    });

    // Compare player count
    results.push({
      field: 'Player Count',
      expected: expected.players.length.toString(),
      actual: generated.players.length.toString(),
      match: expected.players.length === generated.players.length
    });

    // Compare each player
    const maxPlayers = Math.max(expected.players.length, generated.players.length);
    for (let i = 0; i < maxPlayers; i++) {
      const expPlayer = expected.players[i];
      const actPlayer = generated.players[i];

      if (expPlayer && actPlayer) {
        // Compare name
        results.push({
          field: `Player ${i + 1} Name`,
          expected: expPlayer.name,
          actual: actPlayer.name,
          match: expPlayer.name === actPlayer.name
        });

        // Compare position ONLY for Dealer, SB, BB (skip other positions)
        const expPos = expPlayer.position?.toLowerCase();
        const actPos = actPlayer.position?.toLowerCase();
        const isButtonPosition = (pos: string | undefined) => {
          if (!pos) return false;
          return pos === 'dealer' || pos === 'sb' || pos === 'bb';
        };

        if (isButtonPosition(expPos) || isButtonPosition(actPos)) {
          results.push({
            field: `Player ${i + 1} Position`,
            expected: expPlayer.position || '(none)',
            actual: actPlayer.position || '(none)',
            match: expPlayer.position === actPlayer.position
          });
        }

        // Compare stack
        results.push({
          field: `Player ${i + 1} Stack`,
          expected: expPlayer.stack.toLocaleString(),
          actual: actPlayer.stack.toLocaleString(),
          match: expPlayer.stack === actPlayer.stack
        });
      } else if (expPlayer) {
        results.push({
          field: `Player ${i + 1}`,
          expected: `${expPlayer.name} (${expPlayer.position || 'no pos'}) ${expPlayer.stack}`,
          actual: '(missing)',
          match: false
        });
      } else if (actPlayer) {
        results.push({
          field: `Player ${i + 1}`,
          expected: '(missing)',
          actual: `${actPlayer.name} (${actPlayer.position || 'no pos'}) ${actPlayer.stack}`,
          match: false
        });
      }
    }

    setComparisonResults(results);
    setShowResults(true);
  };

  const allMatch = comparisonResults.every(r => r.match);
  const matchCount = comparisonResults.filter(r => r.match).length;
  const totalCount = comparisonResults.length;

  const copyFailuresOnly = async () => {
    const failures = comparisonResults.filter(r => !r.match);
    if (failures.length === 0) {
      alert('✅ No failures to copy - all fields match!');
      return;
    }

    // Format failures as a single-cell string (newlines will appear in one cell)
    const failureText = failures
      .map(f => `${f.field}: Expected "${f.expected}" but got "${f.actual}"`)
      .join('\n');

    try {
      await navigator.clipboard.writeText(failureText);
      alert(`✅ Copied ${failures.length} failure(s) to clipboard!\n\nYou can paste this into a single Google Sheets cell.`);
    } catch (error) {
      console.error('Failed to copy failures:', error);
      alert('❌ Failed to copy to clipboard');
    }
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-xl shadow-2xl max-w-4xl w-full max-h-[90vh] overflow-hidden flex flex-col">
        {/* Header */}
        <div className="bg-gradient-to-r from-purple-600 to-indigo-600 p-6">
          <div className="flex justify-between items-center">
            <h2 className="text-2xl font-bold text-white flex items-center gap-3">
              <span>🔍</span>
              <span>Hand Comparison Tool</span>
            </h2>
            <button
              onClick={onClose}
              className="text-white hover:text-gray-200 text-3xl font-bold leading-none"
            >
              ×
            </button>
          </div>
          <p className="text-white/90 mt-2 text-sm">
            Compare the generated next hand with expected output from another tool
          </p>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6">
          <div className="space-y-6">
            {/* Generated Hand (Read-only) */}
            <div>
              <label className="block text-sm font-bold text-gray-700 mb-2">
                Generated Hand (Our Tool)
              </label>
              <pre className="bg-gray-100 border-2 border-gray-300 rounded-lg p-4 font-mono text-xs leading-relaxed whitespace-pre-wrap">
                {generatedHand}
              </pre>
            </div>

            {/* Expected Hand (Input) */}
            <div>
              <label className="block text-sm font-bold text-gray-700 mb-2">
                Expected Hand (From Other Tool)
              </label>
              <textarea
                value={expectedHand}
                onChange={(e) => setExpectedHand(e.target.value)}
                className="w-full px-4 py-3 border-2 border-gray-300 rounded-lg font-mono text-xs leading-relaxed resize-y"
                rows={15}
                placeholder="Paste the expected hand output here..."
              />
            </div>

            {/* Compare Button */}
            <div className="flex justify-center">
              <button
                onClick={compareHands}
                className="px-8 py-3 bg-gradient-to-r from-purple-600 to-indigo-600 text-white font-bold rounded-lg hover:from-purple-700 hover:to-indigo-700 transition-all shadow-lg hover:shadow-xl"
              >
                🔍 Compare Hands
              </button>
            </div>

            {/* Comparison Results */}
            {showResults && (
              <div className="mt-6">
                {/* Summary */}
                <div className={`p-4 rounded-lg mb-4 ${allMatch ? 'bg-green-100 border-2 border-green-500' : 'bg-red-100 border-2 border-red-500'}`}>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <span className="text-3xl">{allMatch ? '✅' : '❌'}</span>
                      <div>
                        <h3 className="text-lg font-bold">
                          {allMatch ? 'Perfect Match!' : 'Differences Found'}
                        </h3>
                        <p className="text-sm">
                          {matchCount} of {totalCount} fields match ({Math.round((matchCount / totalCount) * 100)}%)
                        </p>
                      </div>
                    </div>
                    {!allMatch && (
                      <button
                        onClick={copyFailuresOnly}
                        className="px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors font-semibold shadow-md whitespace-nowrap"
                      >
                        📋 Copy Failures Only
                      </button>
                    )}
                  </div>
                </div>

                {/* Detailed Results */}
                <div className="border-2 border-gray-300 rounded-lg overflow-hidden">
                  <table className="w-full text-sm">
                    <thead className="bg-gray-200">
                      <tr>
                        <th className="px-4 py-2 text-left font-bold">Field</th>
                        <th className="px-4 py-2 text-left font-bold">Expected</th>
                        <th className="px-4 py-2 text-left font-bold">Actual</th>
                        <th className="px-4 py-2 text-center font-bold">Status</th>
                      </tr>
                    </thead>
                    <tbody>
                      {comparisonResults.map((result, index) => (
                        <tr
                          key={index}
                          className={`${result.match ? 'bg-green-50' : 'bg-red-50'} border-t border-gray-300`}
                        >
                          <td className="px-4 py-2 font-medium">{result.field}</td>
                          <td className="px-4 py-2 font-mono">{result.expected}</td>
                          <td className="px-4 py-2 font-mono">{result.actual}</td>
                          <td className="px-4 py-2 text-center">
                            <span className="text-xl">{result.match ? '✅' : '❌'}</span>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="bg-gray-100 px-6 py-4 flex justify-end gap-3">
          <button
            onClick={onClose}
            className="px-6 py-2 bg-gray-500 text-white rounded-lg hover:bg-gray-600 transition-colors font-semibold"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
